name: "Poetry CodeArtifact publish Action"
description: Github Action to build and publish a Python package to AWS CodeArtifact with Poetry
inputs:
  working-directory:
    description: An optional working directory to cd into before building
    required: false
    default: .
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  aws-region:
    description: AWS Region, e.g. eu-central-1
    required: true
  role-to-assume:
    description: IAM Role to assume that has access to CodeArtifact
    required: false
  codeartifact-domain:
    description: CodeArtifact domain to which the package repository belongs
    required: true
  codeartifact-domain-owner:
    description: Owner (AWS Account) of the CodeArtifact domain
    required: true
  codeartifact-repository:
    description: CodeArtifact repository to which to publish the Python package
    required: true
  python-version:
    description: which Python version to use
    required: false
    default: "3.10"
  poetry-version:
    description: which Poetry version to use
    required: false
    default: "1.3.2"
  skip-checkout:
    description: if code checkout should be skipped. Useful if you already do a code checkout earlier in your workflow
    required: false
    default: "false" # warning: composite actions only allow strings as input!
  add-py-typed-marker:
    description: |
      If true, adds a `py.typed` marker file before publishing, to indicate to package consumers that your package is 
      typed. See also: https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-type-information
    required: false
    default: "false" # warning: composite actions only allow strings as input!

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Check out
      uses: actions/checkout@v3
      if: ${{ inputs.skip-checkout == 'false' }}
      with:
        fetch-depth: 0

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}

    - name: Authenticate to CodeArtifact
      uses: source-ag/codeartifact-login-action@main
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        codeartifact-domain: ${{ inputs.codeartifact-domain }}
        codeartifact-domain-owner: ${{ inputs.codeartifact-domain-owner }}
        codeartifact-repository: ${{ inputs.codeartifact-repository }}
        configure-poetry: true

    - name: Add py.typed marker
      if: ${{ inputs.add-py-typed-marker == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: touch py.typed

    - name: Publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry build
        poetry publish -r ${{ inputs.codeartifact-repository }}
